$(document).ready(function(){
    $("#pic1").mouseenter(function(){
        $('#picss').attr("src",$(this).attr('src'));
    });
});

$(document).ready(function(){
    $("#pic2").mouseenter(function(){
        $('#picss').attr("src",$(this).attr('src'));
    });
});

$(document).ready(function(){
    $("#pic3").mouseenter(function(){
        $('#picss').attr("src",$(this).attr('src'));
    });
});
$(document).ready(function(){
    $("#pic4").mouseenter(function(){
        $('#picss').attr("src",$(this).attr('src'));
    });
});
$(document).ready(function(){
    $("#pic5").mouseenter(function(){
        $('#picss').attr("src",$(this).attr('src'));
    });
});
$(document).ready(function(){
    $("#pic6").mouseenter(function(){
        $('#picss').attr("src",$(this).attr('src'));
    });
});
$(document).ready(function(){
    $("#pic7").mouseenter(function(){
        $('#picss').attr("src",$(this).attr('src'));
    });
});